# ----------------------------
# Makefile Options
# ----------------------------

NAME = BLOCKR
ICON = icon.png
DESCRIPTION = "Ian's Blockrush"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
